// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back. Use to verify connectivity to the Sovereign OS MCP server.",
  inputSchema: { text: z.string().min(1).describe("Text to echo back.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/list_canon_pages.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.8";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_canon_pages_default = defineTool2({
  name: "list_canon_pages",
  title: "List canon pages",
  description: "List active Sovereign OS canon pages (Watershed Thesis, Fire Defense, Below the Radar, Regenerative Gem, etc.) with slugs, audiences, and navigation notes.",
  inputSchema: {
    status: z2.enum(["active", "draft", "retired", "any"]).optional().describe("Filter by status. Defaults to active.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    let q = sb.from("canon_pages").select("slug,title,url,audience,summary,navigation_notes,primary_regions,secondary_regions,status").order("sort_order", { ascending: true });
    const effective = status ?? "active";
    if (effective !== "any") q = q.eq("status", effective);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { pages: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list_my_facts.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.110.8";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_my_facts_default = defineTool3({
  name: "list_my_facts",
  title: "List my Gemma facts",
  description: "List durable facts Gemma remembers about the signed-in operator (from gemma_facts). Optionally filter by room scope.",
  inputSchema: {
    scope_room: z3.string().optional().describe("Optional room slug (e.g. 'outreach', 'radar') to scope facts to."),
    include_retired: z3.boolean().optional().describe("Include retired facts. Defaults to false.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ scope_room, include_retired }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    let q = sb.from("gemma_facts").select("id,fact,scope_room,pinned,confidence,created_at,retired_at").eq("user_id", ctx.getUserId()).order("pinned", { ascending: false }).order("created_at", { ascending: false });
    if (scope_room) q = q.eq("scope_room", scope_room);
    if (!include_retired) q = q.is("retired_at", null);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { facts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/remember_fact.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.110.8";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var remember_fact_default = defineTool4({
  name: "remember_fact",
  title: "Remember a fact",
  description: "Save a durable fact into Gemma's memory layer (gemma_facts) for the signed-in operator. Optionally scope it to a room.",
  inputSchema: {
    fact: z4.string().trim().min(3).describe("The fact to remember (atomic, one idea)."),
    scope_room: z4.string().optional().describe("Optional room slug to scope the fact (e.g. 'outreach'). Omit for global."),
    pinned: z4.boolean().optional().describe("Pin the fact so it always injects. Defaults to false.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ fact, scope_room, pinned }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("gemma_facts").insert({
      user_id: ctx.getUserId(),
      fact,
      scope_room: scope_room ?? null,
      pinned: pinned ?? false
    }).select("id,fact,scope_room,pinned,created_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Saved fact ${data.id}` }],
      structuredContent: { fact: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "spoiizdwriqfspehbcwp";
var mcp_default = defineMcp({
  name: "sovereign-os-mcp",
  title: "Sovereign OS MCP",
  version: "0.1.0",
  instructions: "Sovereign OS coordination infrastructure for Fellowship of Living Systems. Tools act as the signed-in operator against their own data. Use `list_canon_pages` to browse canon (Watershed Thesis, Fire Defense, Below the Radar, Regenerative Gem). Use `list_my_facts` and `remember_fact` to read and extend Gemma's durable memory layer. Use `echo` to verify connectivity.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [echo_default, list_canon_pages_default, list_my_facts_default, remember_fact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
